---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - blocky
  - cloudflare-ddns
  - external-dns
  # - ingress-nginx
  - k8s-gateway
  - traefik
  - wildcard-certificate
