---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - blackbox-exporter
  - grafana
  - kube-prometheus-stack
  - loki
  - network-ups-tools
  - promtail
  - snmp-exporter-mikrotik
  - speedtest-exporter
  - thanos
