---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - namespace.yaml
  - blackbox-exporter
  - grafana
  - kube-prometheus-stack
  # - loki
  - network-ups-tools
  - snmp-exporter
  - speedtest-exporter
  - thanos
  # - vector
