---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secret.sops.yaml
  - flux.yaml
  - home-ops.yaml
  - kube-prometheus-stack.yaml
  - mongodb-community-operator.yaml
  - openebs-zfs-localpv.yaml
