---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: openebs-monitoring-charts
  namespace: flux-system
spec:
  interval: 10m
  url: https://openebs.github.io/monitoring/
  timeout: 3m