---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: discord
resources:
  - namespace.yaml
  - secret.sops.yaml
  - discord-stock-ticker
  - puppeteer
  - whalestream-bot
  - ws-staging-bot
  - wyoa-bot
