---
# https://rancher.com/docs/k3s/latest/en/installation/install-options/server-config/
# https://github.com/PyratLabs/ansible-role-k3s#server-control-plane-configuration

# Define the host as control plane nodes
k3s_control_node: true

# S3 snapshot settings for etcd
k3s_etcd_snapshot_schedule_cron: "0 */4 * * *"
k3s_etcd_snapshot_retention: 24
k3s_etcd_s3_endpoint: "s3.{{ domain }}"
k3s_etcd_s3_bucket: k3s
k3s_etcd_s3: true

# k3s settings for all control-plane nodes
k3s_server:
  node-ip: "{{ ansible_host }}"
  tls-san:
    - "{{ k3s_registration_address }}"
  docker: false
  flannel-backend: "none" # This needs to be in quotes
  disable:
    - flannel
    - traefik
    - servicelb
    - metrics-server
    - local-storage
  disable-network-policy: true
  disable-cloud-controller: true
  disable-kube-proxy: true

  write-kubeconfig-mode: "644"
  etcd-expose-metrics: true

  cluster-cidr: "{{ k3s_cluster_cidr }}"
  service-cidr: "{{ k3s_service_cidr }}"

  kubelet-arg:
    - "feature-gates=MixedProtocolLBService=true"
    # Allow pods to be rescheduled quicker in the case of a node failure
    # https://github.com/k3s-io/k3s/issues/1264
    - "node-status-update-frequency=4s"
  kube-controller-manager-arg:
    - "allocate-node-cidrs"
    # Required to monitor component with kube-prometheus-stack
    - "bind-address=0.0.0.0"
    # Allow pods to be rescheduled quicker in the case of a node failure
    # https://github.com/k3s-io/k3s/issues/1264
    - "node-monitor-period=4s"
    - "node-monitor-grace-period=16s"
    - "pod-eviction-timeout=20s"
  kube-proxy-arg:
    # Required to monitor component with kube-prometheus-stack
    - "metrics-bind-address=0.0.0.0"
  kube-scheduler-arg:
    # Required to monitor component with kube-prometheus-stack
    - "bind-address=0.0.0.0"
  kube-apiserver-arg:
    # Allow pods to be rescheduled quicker in the case of a node failure
    # https://github.com/k3s-io/k3s/issues/1264
    - "default-not-ready-toleration-seconds=20"
    - "default-unreachable-toleration-seconds=20"
