---
- name: email | install mail packages
  ansible.builtin.apt:
    update_cache: yes
    pkg:
      - mailutils
      - msmtp
      - msmtp-mta
      - bsd-mailx
    state: present

- name: email | configure aliases
  ansible.builtin.template:
    src: aliases.j2
    dest: /etc/aliases
    mode: 0644

- name: email | configure mail
  ansible.builtin.template:
    src: mail.rc.j2
    dest: /etc/mail.rc
    mode: 0644

- name: email | configure msmtpd
  ansible.builtin.template:
    src: msmtprc.j2
    dest: /etc/msmtprc
    mode: 0644

- name: email | restart msmtpd service
  ansible.builtin.systemd:
    name: msmtpd
    daemon_reload: true
    enabled: true
    state: restarted
