---
collections:
  - name: ansible.posix
    version: 1.6.2
  - name: community.docker
    version: 3.5.0
  - name: community.general
    version: 8.1.0
  - name: community.routeros
    version: 2.11.0
  - name: community.sops
    version: 1.6.7
  - name: kubernetes.core
    version: 3.0.0
roles:
  - src: xanmanning.k3s
    version: v3.4.3
  - src: https://github.com/mrlesmithjr/ansible-zfs.git
    scm: git
    name: mrlesmithjr.zfs
    version: b80e84d6938eb7730faeffc7ff7d8aa06ad5bef7
