---
collections:
  - name: ansible.posix
    version: 1.4.0
  - name: community.docker
    version: 2.6.0
  - name: community.general
    version: 5.2.0
  - name: community.routeros
    version: 2.1.0
  - name: community.sops
    version: 1.2.3
  - name: kubernetes.core
    version: 2.3.2
roles:
  - src: xanmanning.k3s
    version: v3.2.0
  - src: https://github.com/mrlesmithjr/ansible-zfs.git
    scm: git
    name: mrlesmithjr.zfs
    version: b80e84d6938eb7730faeffc7ff7d8aa06ad5bef7
