---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bitnami-charts.yaml
  - cilium-charts.yaml
  - external-dns-charts.yaml
  - grafana-charts.yaml
  - hajimari-charts.yaml
  - ingress-nginx-charts.yaml
  - jetstack-charts.yaml
  - k8s-at-home-charts.yaml
  - k8s-gateway-charts.yaml
  - kasten-charts.yaml
  - metallb-charts.yaml
  - metrics-server-charts.yaml
  - minio-charts.yaml
  - mongodb-charts.yaml
  - openebs-zfs-localpv-charts.yaml
  - prometheus-community-charts.yaml
  - stakater-charts.yaml
  - vector-charts.yaml
