---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: radarr-config-v1
  namespace: media
  labels:
    k10.kasten.io/backup: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: openebs-zfspv-ssd
