---
- name: kubeconfig | copy kubeconfig locally to /tmp
  run_once: true
  ansible.builtin.fetch:
    src: "/etc/rancher/k3s/k3s.yaml"
    dest: "/tmp/kubeconfig"
    flat: true
  when:
    - k3s_control_node is defined
    - k3s_control_node

- name: kubeconfig | update kubeconfig with the right address
  delegate_to: localhost
  become: false
  run_once: true
  ansible.builtin.replace:
    path: "/tmp/kubeconfig"
    regexp: "https://127.0.0.1:6443"
    replace: "https://{{ kubevip_address }}:6443"
