---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - databases
  - flux-system
  - home
  - kube-system
  - media
  - monitoring
  - networking
  - security
  - system-upgrade
