---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: thanos-receive.rules
  namespace: monitoring
spec:
  groups:
  - name: thanos-receive.rules
    rules:
    - alert: ThanosReceiveIsDown
      annotations:
        description: ThanosReceive has disappeared. Prometheus target for the component
          cannot be discovered.
        runbook_url: https://github.com/thanos-io/thanos/tree/main/mixin/runbook.md#alert-name-thanosreceiveisdown
        summary: Thanos component has disappeared.
      expr: |
        absent(up{job=~".*thanos-receive.*"} == 1)
      for: 5m
      labels:
        severity: critical
    - alert: ThanosReceiveHttpRequestErrorRateHigh
      annotations:
        description: Thanos Receive {{$labels.job}} is failing to handle {{$value | humanize}}%
          of requests.
        runbook_url: https://github.com/thanos-io/thanos/tree/main/mixin/runbook.md#alert-name-thanosreceivehttprequesterrorratehigh
        summary: Thanos Receive is failing to handle requests.
      expr: |
        (
          sum by (job) (rate(http_requests_total{code=~"5..", job=~".*thanos-receive.*", handler="receive"}[5m]))
        /
          sum by (job) (rate(http_requests_total{job=~".*thanos-receive.*", handler="receive"}[5m]))
        ) * 100 > 5
      for: 5m
      labels:
        severity: critical
    - alert: ThanosReceiveHttpRequestLatencyHigh
      annotations:
        description: Thanos Receive {{$labels.job}} has a 99th percentile latency of {{
          $value }} seconds for requests.
        runbook_url: https://github.com/thanos-io/thanos/tree/main/mixin/runbook.md#alert-name-thanosreceivehttprequestlatencyhigh
        summary: Thanos Receive has high HTTP requests latency.
      expr: |
        (
          histogram_quantile(0.99, sum by (job, le) (rate(http_request_duration_seconds_bucket{job=~".*thanos-receive.*", handler="receive"}[5m]))) > 10
        and
          sum by (job) (rate(http_request_duration_seconds_count{job=~".*thanos-receive.*", handler="receive"}[5m])) > 0
        )
      for: 10m
      labels:
        severity: critical
    - alert: ThanosReceiveHighReplicationFailures
      annotations:
        description: Thanos Receive {{$labels.job}} is failing to replicate {{$value |
          humanize}}% of requests.
        runbook_url: https://github.com/thanos-io/thanos/tree/main/mixin/runbook.md#alert-name-thanosreceivehighreplicationfailures
        summary: Thanos Receive is having high number of replication failures.
      expr: |
        thanos_receive_replication_factor > 1
          and
        (
          (
            sum by (job) (rate(thanos_receive_replications_total{result="error", job=~".*thanos-receive.*"}[5m]))
          /
            sum by (job) (rate(thanos_receive_replications_total{job=~".*thanos-receive.*"}[5m]))
          )
          >
          (
            max by (job) (floor((thanos_receive_replication_factor{job=~".*thanos-receive.*"}+1) / 2))
          /
            max by (job) (thanos_receive_hashring_nodes{job=~".*thanos-receive.*"})
          )
        ) * 100
      for: 5m
      labels:
        severity: warning
    - alert: ThanosReceiveHighForwardRequestFailures
      annotations:
        description: Thanos Receive {{$labels.job}} is failing to forward {{$value | humanize}}%
          of requests.
        runbook_url: https://github.com/thanos-io/thanos/tree/main/mixin/runbook.md#alert-name-thanosreceivehighforwardrequestfailures
        summary: Thanos Receive is failing to forward requests.
      expr: |
        (
          sum by (job) (rate(thanos_receive_forward_requests_total{result="error", job=~".*thanos-receive.*"}[5m]))
        /
          sum by (job) (rate(thanos_receive_forward_requests_total{job=~".*thanos-receive.*"}[5m]))
        ) * 100 > 20
      for: 5m
      labels:
        severity: info
    - alert: ThanosReceiveHighHashringFileRefreshFailures
      annotations:
        description: Thanos Receive {{$labels.job}} is failing to refresh hashring file,
          {{$value | humanize}} of attempts failed.
        runbook_url: https://github.com/thanos-io/thanos/tree/main/mixin/runbook.md#alert-name-thanosreceivehighhashringfilerefreshfailures
        summary: Thanos Receive is failing to refresh hasring file.
      expr: |
        (
          sum by (job) (rate(thanos_receive_hashrings_file_errors_total{job=~".*thanos-receive.*"}[5m]))
        /
          sum by (job) (rate(thanos_receive_hashrings_file_refreshes_total{job=~".*thanos-receive.*"}[5m]))
        > 0
        )
      for: 15m
      labels:
        severity: warning
    - alert: ThanosReceiveConfigReloadFailure
      annotations:
        description: Thanos Receive {{$labels.job}} has not been able to reload hashring
          configurations.
        runbook_url: https://github.com/thanos-io/thanos/tree/main/mixin/runbook.md#alert-name-thanosreceiveconfigreloadfailure
        summary: Thanos Receive has not been able to reload configuration.
      expr: avg by (job) (thanos_receive_config_last_reload_successful{job=~".*thanos-receive.*"})
        != 1
      for: 5m
      labels:
        severity: warning
    - alert: ThanosReceiveNoUpload
      annotations:
        description: Thanos Receive {{$labels.instance}} has not uploaded latest data
          to object storage.
        runbook_url: https://github.com/thanos-io/thanos/tree/main/mixin/runbook.md#alert-name-thanosreceivenoupload
        summary: Thanos Receive has not uploaded latest data to object storage.
      expr: |
        (up{job=~".*thanos-receive.*"} - 1)
        + on (job, instance) # filters to only alert on current instance last 3h
        (sum by (job, instance) (increase(thanos_shipper_uploads_total{job=~".*thanos-receive.*"}[3h])) == 0)
      for: 3h
      labels:
        severity: critical
    - alert: ThanosReceiveTrafficBelowThreshold
      annotations:
        description: At Thanos Receive {{$labels.job}} in {{$labels.namespace}} , the
          average 1-hr avg. metrics ingestion rate  is {{$value | humanize}}% of 12-hr
          avg. ingestion rate.
        runbook_url: https://github.com/thanos-io/thanos/tree/main/mixin/runbook.md#alert-name-thanosreceivetrafficbelowthreshold
        summary: Thanos Receive is experiencing low avg. 1-hr ingestion rate relative
          to avg. 12-hr ingestion rate.
      expr: |
        (
          avg_over_time(rate(http_requests_total{job=~".*thanos-receive.*", code=~"2..", handler="receive"}[5m])[1h:5m])
        /
          avg_over_time(rate(http_requests_total{job=~".*thanos-receive.*", code=~"2..", handler="receive"}[5m])[12h:5m])
        ) * 100 < 50
      for: 1h
      labels:
        severity: warning
    - expr: |
        (
          sum by (job) (rate(grpc_server_handled_total{grpc_code=~"Unknown|ResourceExhausted|Internal|Unavailable|DataLoss|DeadlineExceeded", job=~".*thanos-receive.*", grpc_type="unary"}[5m]))
        /
          sum by (job) (rate(grpc_server_started_total{job=~".*thanos-receive.*", grpc_type="unary"}[5m]))
        )
      record: :grpc_server_failures_per_unary:sum_rate
    - expr: |
        (
          sum by (job) (rate(grpc_server_handled_total{grpc_code=~"Unknown|ResourceExhausted|Internal|Unavailable|DataLoss|DeadlineExceeded", job=~".*thanos-receive.*", grpc_type="server_stream"}[5m]))
        /
          sum by (job) (rate(grpc_server_started_total{job=~".*thanos-receive.*", grpc_type="server_stream"}[5m]))
        )
      record: :grpc_server_failures_per_stream:sum_rate
    - expr: |
        (
          sum by (job) (rate(http_requests_total{handler="receive", job=~".*thanos-receive.*", code!~"5.."}[5m]))
        /
          sum by (job) (rate(http_requests_total{handler="receive", job=~".*thanos-receive.*"}[5m]))
        )
      record: :http_failure_per_request:sum_rate
    - expr: |
        histogram_quantile(0.99,
          sum by (job, le) (rate(http_request_duration_seconds_bucket{handler="receive", job=~".*thanos-receive.*"}[5m]))
        )
      labels:
        quantile: "0.99"
      record: :http_request_duration_seconds:histogram_quantile
    - expr: |
        (
          sum by (job) (rate(thanos_receive_replications_total{result="error", job=~".*thanos-receive.*"}[5m]))
        /
          sum by (job) (rate(thanos_receive_replications_total{job=~".*thanos-receive.*"}[5m]))
        )
      record: :thanos_receive_replication_failure_per_requests:sum_rate
    - expr: |
        (
          sum by (job) (rate(thanos_receive_forward_requests_total{result="error", job=~".*thanos-receive.*"}[5m]))
        /
          sum by (job) (rate(thanos_receive_forward_requests_total{job=~".*thanos-receive.*"}[5m]))
        )
      record: :thanos_receive_forward_failure_per_requests:sum_rate
    - expr: |
        (
          sum by (job) (rate(thanos_receive_hashrings_file_errors_total{job=~".*thanos-receive.*"}[5m]))
        /
          sum by (job) (rate(thanos_receive_hashrings_file_refreshes_total{job=~".*thanos-receive.*"}[5m]))
        )
      record: :thanos_receive_hashring_file_failure_per_refresh:sum_rate