---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - namespace.yaml
  - _pvc
  - lidarr
  - plex
  - prowlarr
  - qbittorrent
  - overseerr
  - radarr
  - sonarr
  - tautulli
