---
- name: samba | install samba packages
  ansible.builtin.apt:
    update_cache: yes
    pkg:
      - samba
      - samba-vfs-modules
    state: present

- name: samba | create users if absent
  shell: >
    (pdbedit --user={{ item.name }} 2>&1 > /dev/null) \
    || (echo {{ item.password }}; echo {{ item.password }}) \
    | smbpasswd -s -a {{ item.name }}
  with_items: "{{ samba_users }}"
  no_log: true
  register: create_user_output
  changed_when: "'Added user' in create_user_output.stdout"
  when:
    - samba_users
    - samba_users | length > 0

- name: samba | configure samba
  ansible.builtin.template:
    src: smb.conf.j2
    dest: /etc/samba/smb.conf
    validate: "testparm -s %s"
    mode: 0644

- name: samba | restart samba service
  ansible.builtin.systemd:
    name: smbd
    daemon_reload: true
    enabled: true
    state: restarted
